import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import Head from "next/head";
import { Header } from "@/components/ui/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link href="/dist/styles.css" rel="stylesheet"></link>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-lg px-2 py-6`}
      >
        <div className="flex flex-col gap-4">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
